baseURL = "https://krishnatej.dev"
languageCode = "en-us"
title = "Krishna Tej"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4
    noClasses = true
    style = "monokai"

[permalinks]
  posts = "/blog/:year/:title/"